services:
  mi-ahorro:
    build: .
    container_name: mi-ahorro
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128M"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://miahorro:${DB_PASSWORD}@postgres:5432/miahorro"
      SESSION_SECRET: "${SESSION_SECRET}"
      NODE_ENV: production
    networks:
      - postgres
      - caddy
    restart: unless-stopped

networks:
  postgres:
    external: true
  caddy:
    external: true
